

```{r}
library(dplyr)
library(tidyverse)
library(DMwR2)
library(caret)
library(ggplot2)
library(GGally)
library(rpart.plot)
````


Data Manipulation
```{r}
data = read.csv("C:\\Users\\kristalowry\\Documents\\DA Data Mining\\FinalProject\\online_shoppers_intention.csv")
df <- data %>% mutate(Revenue = as.factor(Revenue),
                      OperatingSystems = as.factor(OperatingSystems),
                      Browser = as.factor(Browser),
                      Region = as.factor(Region),
                      VisitorType = as.factor(VisitorType),
                      TrafficType = as.factor(TrafficType),
                      Weekend = as.factor(ifelse(Weekend == TRUE, 1, 0)),
                      Month = as.factor(recode(Month, Feb = 2,Mar = 3,May = 5,June = 6,Jul = 7,
                                               Aug = 8,  Sep = 9,Oct = 10,Nov = 11,Dec = 12)),
                      #totals
                      TotalDuration = Informational_Duration 
                                      + ProductRelated_Duration + Administrative_Duration,
                      TotalPages =  Informational + ProductRelated + Administrative,

                      #binaries
                      Revenue_binary =  ifelse(Revenue == TRUE, 1, 0),
                      VisitorType_Returning_binary = ifelse(VisitorType == "Returning_Visitor", 1, 0),                 
                      Weekend_binary = ifelse(Weekend == 1, 1, 0),
                      ProductRelated_binary = ifelse(ProductRelated_Duration > 0, 1, 0),
                      Administrative_binary = ifelse(Administrative_Duration > 0, 1, 0),
                      Informational_binary = ifelse(Informational_Duration > 0, 1, 0))
                      
df <-  df %>% mutate(special_day_binary = (
                        case_when(SpecialDay == 0 ~ 1, .default = 0)))

df_fact <- df %>% select(-Revenue_binary, -Weekend_binary, -TrafficType, -PageValues, -BounceRates, -ExitRates, -SpecialDay,-VisitorType_Returning_binary) %>% mutate(special_day_binary = as.factor(special_day_binary)) 
df_fact <- df_fact %>% filter(VisitorType != "Other")

df_fact %>% glimpse()

```


Summarize conversions by feature.
```{r}
df_sum <- df %>% group_by(Revenue)  %>%
              summarize(total_count = n(),
              avg_duration = round(mean(TotalDuration),digits=2),
              sum_pages = round(sum(TotalPages),digits=2),
              page_per_user = sum_pages / total_count,
              weekend_true = sum(Weekend_binary),
              perc_weekend = round((weekend_true / total_count),digits = 2 ),
              returning = sum(case_when(VisitorType == "Returning_Visitor" ~ 1, .default = 0)),
              new = sum(case_when(VisitorType == "New_Visitor" ~ 1, .default = 0)),
              perc_returning = round(returning / sum(returning + new),digits = 2),
              special_day_total = sum(special_day_binary),
              perc_on_special_day =   round((special_day_total / total_count),digits=2))

df_sum %>% select(1:3,5,7,8:10,12)

```

Check out conversion rates
```{r}
df_sum_op <- df %>% group_by(OperatingSystems)  %>%
 dplyr:: summarize(rev_true = sum(Revenue_binary),
            total_count = n(),
            conv_rate = round((rev_true / total_count), digits=2)) 

ggplot(df_sum_op, aes(x = total_count, y = conv_rate, color = OperatingSystems, size=total_count, label=OperatingSystems )) +
  geom_point() + geom_text(hjust=2,vjust=2) + labs(title ="Conversion Rate by Operating System", x ="Total Sessions") 


df_sum_reg <- df %>% group_by(Region)  %>%
  dplyr::summarize(rev_true = sum(Revenue_binary),
            total_count = n(),
            conv_rate = round((rev_true / total_count), digits=2))

ggplot(df_sum_reg, aes(x = total_count, y = conv_rate, color = Region, size=total_count, label=Region )) +
  geom_point() + geom_text(hjust=2,vjust=2) + labs(title ="Conversion Rate by Region", x ="Total Sessions") 


df_sum_mo <- df %>% group_by(Month)  %>%
  dplyr::summarize(rev_true = sum(Revenue_binary),
            total_count = n(),
            conv_rate = round((rev_true / total_count), digits=2))

ggplot(df_sum_mo, aes(x = total_count, y = conv_rate, color = Month, size=total_count, label=Month)) +
  geom_point() + geom_text(hjust=2,vjust=2)   + labs(title ="Conversion Rate by Month", x ="Total Sessions") 


df_sum_tp <- df %>% group_by(TotalPages)  %>%
  dplyr::summarize(rev_true = sum(Revenue_binary),
            total_count = n(),
            conv_rate = rev_true / total_count)


ggplot(df_sum_tp, aes(x = TotalPages, y = conv_rate, color = total_count)) +
  geom_point()  + 
  geom_jitter(width = 5) +
  geom_smooth(method = "loess", formula = y ~ x) +
  labs(title ="Conversion Rate by TotalPages", x ="Total Pages") +
  scale_x_continuous(n.breaks = 10,limits = c(NA,100)) +
       scale_y_continuous(n.breaks = 5,limits = c(NA,.5) )




```


normalize the data and split
```{r}

set.seed(1234)
in_train = createDataPartition(y = df_fact$Revenue,
p = 0.8, list = FALSE)
r_train = df_fact[in_train, ]
r_test = df_fact[-in_train, ]
training_set = select(r_train, -Revenue)

preprocess_steps = preProcess(r_train, method = c("center","scale"))
r_train_proc = predict(preprocess_steps, newdata = r_train)
r_test_proc = predict(preprocess_steps, newdata = r_test)
training_set_proc = select(r_train_proc, -Revenue)


```


Logistic regression. 
```{r}
set.seed(1234)
lr_model = train(Revenue ~ ., 
                 family = "binomial",
                 data = r_train,
                 method = "glm", 
                 trControl = trainControl(method = "cv",
                                          number = 5,
                                          sampling = "smote"
                 ),
                 na.action = na.omit)
#k nearest neighbors
set.seed(1234)
default_knn_mod = train(
  Revenue ~ .,
  data = r_train,
  method = "knn",
  trControl = trainControl(method = "cv",number = 5, sampling = "smote")
)
#5
plot(default_knn_mod)
default_knn_mod$results
default_knn_mod$bestTune
predictions_knn = predict(default_knn_mod, newdata = r_test)
confusionMatrix(predictions_knn, r_test$Revenue)

lr_model$results
lr_model$finalModel
summary(lr_model)
predictions = predict(lr_model, newdata = r_test)
confusionMatrix(predictions, r_test$Revenue)
plot(varImp(lr_model))

```




Bagged model decision tree works but the model is really poor (specificity)
```{r}
set.seed(1234)
bagged_model = train(y=r_train$Revenue, 
                           trControl = trainControl(method = "cv",
                                                    number = 5),
                          x = training_set, method = "treebag")

bagged_predictions = predict(bagged_model, r_test)
confusionMatrix(bagged_predictions, r_test$Revenue)
plot(varImp(bagged_model))


#specificity is really really bad. Not usable

```


Random Forest using Ranger works okay
```{r}
library(ranger)
set.seed(1234)
features <- setdiff(names(r_train), "Revenue")
x <- r_train[, features]
y <- r_train$Revenue
# set up 5-fold cross validation procedure
train_control <- trainControl(method = "cv",
                              number = 5,
#                              verboseIter = TRUE,
                              savePredictions = "final")
#ran it once without tuneGrid and these were the best params 
rf_grid <- expand.grid(mtry = c(5),
                       splitrule = c("extratrees"),
                       min.node.size = c(2))
rf.model <- train(
                  x = x,
                  y = y,
                  method = "ranger",
                  trControl = train_control,
                  tuneGrid = rf_grid,
                  )
rf.model
rf_predictions = predict(rf.model, r_test)
confusionMatrix(rf_predictions, r_test$Revenue)


```



Compare models
```{r}

confusionMatrix(predictions, r_test$Revenue)
confusionMatrix(predictions_knn, r_test$Revenue)
confusionMatrix(bagged_predictions, r_test$Revenue)
confusionMatrix(rf_predictions, r_test$Revenue)

results = resamples(list(knn = default_knn_mod, rf.model= rf.model,lr_model = lr_model, bagged_model=bagged_model))
summary(results)
dotplot(results)

```




